version: "3.8"

services: 
  rest_api:
    image: estellapaula/video_processing:first_version
    ports:
      - 5000:5000
    expose:
      - 5000
    environment:
      FLASK_APP: project/__init__.py
      FLASK_ENV: development
      DATABASE_URL: postgresql://admin:secret@db:5432/postgres
      SQL_HOST: db
      SQL_PORT: 5432
      DATABASE: postgres
    networks:
      - server_network
      - admin_network
    deploy:
      replicas: 3
      placement:
        max_replicas_per_node: 2
      restart_policy:
        condition: on-failure
    depends_on:
      - db

  scraper_daemon:
    image: estellapaula/video_processing:first_version_scraper
    networks:
      - admin_network
    deploy:
      restart_policy:
          condition: on-failure
      placement:
        constraints: [node.role == manager]
    depends_on:
      - rest_api
    

  db:
    image: postgres:12.2
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - server_network
      - front_end_network
    ports:
      - 5432:5432
    expose:
      -  5432

  grafana:
    image: grafana/grafana:latest
    hostname: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=secret
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
    ports:
      - 3000:3000
    networks:
      - front_end_network
    volumes:
      - grafana-log:/var/log/grafana
      # - ~/grafana/grafana.ini:/etc/grafana/grafana.ini
      # - ~/grafana/provisioning/:/etc/grafana/provisioning/
      # - ~/grafana/dashboards/:/etc/grafana/dashboards/
    depends_on:
      - db


  nginx:
    image: estellapaula/video_processing:first_version_nginx
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]
    ports:
      - 80:80
      - 443:443
    expose:
      - 80:80
      - 443:443
    depends_on:
      - rest_api
    networks:
      - admin_network

 
  agent:
    image: portainer/agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    image: portainer/portainer-ce
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - "9000:9000"
      - "8000:8000"
    volumes:
      - portainer_data:/data
    networks:
      - agent_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

volumes:
  grafana-log:
  portainer_data:
  log-data:
  db-data:
    driver: local

networks:
  db_network:
  server_network:
    driver: overlay
  admin_network:
    driver: overlay
  front_end_network:
    driver: overlay
  agent_network:
    driver: overlay
    attachable: true