{
 "title": "System overview",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Time transcoding",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  avg(time_transcoding) AS \"av1\"\nFROM \"jobResults\"\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  codec = 'av1'\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  avg(time_transcoding) AS \"vp9\"\nFROM \"jobResults\"\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  codec = 'vp9'\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  avg(time_transcoding) AS \"x256\"\nFROM \"jobResults\"\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  codec = 'x256'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Worker sessions",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  id AS \"IDLE\"\nFROM workers\nWHERE\n  idle = 'true'\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  id AS \"BUSY\"\nFROM workers\nWHERE\n  idle = 'false'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Boss sessions",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  id AS \"IDLE\"\nFROM bosses\nWHERE\n  idle = 'true'\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  id AS \"BUSY\"\nFROM bosses\nWHERE\n  idle = 'false'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Time I/O",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  avg(time_io) AS \"av1\"\nFROM \"jobResults\"\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  codec = 'av1'\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  avg(time_io) AS \"vp9\"\nFROM \"jobResults\"\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  codec = 'vp9'\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  avg(time_io) AS \"x256\"\nFROM \"jobResults\"\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  codec = 'x256'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Jobs overview",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT codec, count(id)\nFROM \"jobResults\"\nGROUP BY codec"
    },
    {
     "rawSql": "SELECT\n  count(id)\nFROM \"jobResults\""
    }
   ]
  }
 ]
}